public class Tester {

    public void testInt(){
        int a=5, b=4, c;

        System.out.println("Integer operations:");
        System.out.println("a="+a);
        System.out.print("b="+b);

        c=a+b;
        System.out.printf("\na+b=%d", c);
        c=a-b;
        System.out.printf("\na-b=%d", c);
        c=a/b;
        System.out.printf("\na/b=%d", c);
        c=a*b;
        System.out.printf("\na*b=%d", c);
        c=a%b;
        System.out.printf("\na%%b=%d", c);
        c=++a+b++;
        --a;
        --b;
        System.out.printf("\n++a+b++=%d", c);
        c=b+++b+++b++;
        b -=3;
        System.out.printf("\nb+++b+++b++=%d", c);
        c=--b+a++;
        b++;
        a--;
        System.out.printf("\n--b+a++=%d", c);
        boolean z=a>b;
        System.out.printf("\na>b-"+ z);
        z=a<=b;
        System.out.printf("\na<=b-"+ z);
        z=a!=b;
        System.out.printf("\na!=b-"+ z);
        z=a<b&&a!=0;
        System.out.printf("\na<b&&a!=0-"+ z);
        z=a>b&&a!=0;
        System.out.printf("\na>b&&a!=0-"+ z);
        z=a<b||a!=0;
        System.out.printf("\na<b||a!=0-"+ z);
        z=a>b||a!=0;
        System.out.printf("\na>b||a!=0-"+ z);
        z=a<b^a!=0;
        System.out.printf("\na<b^a!=0-"+ z);
        z=a>b^a!=0;
        System.out.printf("\na>b^a!=0-"+ z);
        z=!(a>b);
        System.out.printf("\n!(a>b)-"+ z);
        z=a<b&a!=0;
        System.out.printf("\na<b&a!=0-"+ z);
        z=a>b&a!=0;
        System.out.printf("\na>b&a!=0-"+ z);
        z=a<b|a!=0;
        System.out.printf("\na<b|a!=0-"+ z);
        z=a>b|a!=0;
        System.out.printf("\na>b|a!=0-"+ z);
        c=~a;
        System.out.printf("\nc=~a, c="+ c);
        c=a>>1;
        System.out.printf("\nc=a>>1, c="+ c);
        c=a<<1;
        System.out.printf("\nc=a<<1, c="+ c);
        c=-a>>>1;
        System.out.printf("\nc=-a>>>1, c="+ c);
        c=a;
        System.out.printf("\nc=a, c="+c);
        a+=2;
        System.out.printf("\na+=2, a="+a);
        a-=2;
        a-=1;
        System.out.printf("\na-=1, a="+a);
        a++;
        a*=2;
        System.out.printf("\na*=2, a="+a);
        a/=2;
        a/=2;
        System.out.printf("\na/=2, a="+a);
        a=5;
        a%=2;
        System.out.printf("\na%%=2, a="+a);
        a=5;
        a<<=1;
        System.out.printf("\na<<=1, a="+a);
        a=5;
        a>>=1;
        System.out.printf("\na>>=1, a="+a);
        a=5;
        a&=3;
        System.out.printf("\na&=3, a="+a);
        a=5;
        a|=3;
        System.out.printf("\na|=3, a="+a);
        a=5;
        a^=3;
        System.out.printf("\na^=3, a="+a);
    }

    public void testByte(){
        byte a=5, b=4, c;

        System.out.println("\nByte operations:");
        System.out.println("a="+a);
        System.out.print("b="+b);

        c=(byte)(a+b);
        System.out.printf("\na+b=%d", c);
        c=(byte)(a-b);
        System.out.printf("\na-b=%d", c);
        c=(byte)(a/b);
        System.out.printf("\na/b=%d", c);
        c=(byte)(a*b);
        System.out.printf("\na*b=%d", c);
        c=(byte)(a%b);
        System.out.printf("\na%%b=%d", c);
        c=(byte)(++a+b++);
        a=5;
        b=4;
        System.out.printf("\n++a+b++=%d", c);
        c=(byte)(b+++b+++b++);
        b =4;
        System.out.printf("\nb+++b+++b++=%d", c);
        c=(byte)(--b+a++);
        b=4;
        a=5;
        System.out.printf("\n--b+a++=%d", c);
        boolean z=a>b;
        System.out.printf("\na>b-"+ z);
        z=a<=b;
        System.out.printf("\na<=b-"+ z);
        z=a!=b;
        System.out.printf("\na!=b-"+ z);
        z=a<b&&a!=0;
        System.out.printf("\na<b&&a!=0-"+ z);
        z=a>b&&a!=0;
        System.out.printf("\na>b&&a!=0-"+ z);
        z=a<b||a!=0;
        System.out.printf("\na<b||a!=0-"+ z);
        z=a>b||a!=0;
        System.out.printf("\na>b||a!=0-"+ z);
        z=a<b^a!=0;
        System.out.printf("\na<b^a!=0-"+ z);
        z=a>b^a!=0;
        System.out.printf("\na>b^a!=0-"+ z);
        z=!(a>b);
        System.out.printf("\n!(a>b)-"+ z);
        z=a<b&a!=0;
        System.out.printf("\na<b&a!=0-"+ z);
        z=a>b&a!=0;
        System.out.printf("\na>b&a!=0-"+ z);
        z=a<b|a!=0;
        System.out.printf("\na<b|a!=0-"+ z);
        z=a>b|a!=0;
        System.out.printf("\na>b|a!=0-"+ z);
        c=(byte)(~a);
        System.out.printf("\nc=~a, c="+ c);
        c=(byte)(a>>1);
        System.out.printf("\nc=a>>1, c="+ c);
        c=(byte)(a<<1);
        System.out.printf("\nc=a<<1, c="+ c);
        c=(byte)(-a>>>1);
        System.out.printf("\nc=-a>>>1, c="+ c);
        c=a;
        System.out.printf("\nc=a, c="+c);
        a+=2;
        System.out.printf("\na+=2, a="+a);
        a-=2;
        a-=1;
        System.out.printf("\na-=1, a="+a);
        a++;
        a*=2;
        System.out.printf("\na*=2, a="+a);
        a/=2;
        a/=2;
        System.out.printf("\na/=2, a="+a);
        a=5;
        a%=2;
        System.out.printf("\na%%=2, a="+a);
        a=5;
        a<<=1;
        System.out.printf("\na<<=1, a="+a);
        a=5;
        a>>=1;
        System.out.printf("\na>>=1, a="+a);
        a=5;
        a&=3;
        System.out.printf("\na&=3, a="+a);
        a=5;
        a|=3;
        System.out.printf("\na|=3, a="+a);
        a=5;
        a^=3;
        System.out.printf("\na^=3, a="+a);
    }

    public void testShort(){
        short a=5, b=4, c;

        System.out.println("\nShort operations:");
        System.out.println("a="+a);
        System.out.print("b="+b);

        c=(short) (a+b);
        System.out.printf("\na+b=%d", c);
        c=(short) (a-b);
        System.out.printf("\na-b=%d", c);
        c=(short) (a/b);
        System.out.printf("\na/b=%d", c);
        c=(short) (a*b);
        System.out.printf("\na*b=%d", c);
        c=(short) (a%b);
        System.out.printf("\na%%b=%d", c);
        c=(short) (++a+b++);
        a=5;
        b=4;
        System.out.printf("\n++a+b++=%d", c);
        c=(short) (b+++b+++b++);
        b =4;
        System.out.printf("\nb+++b+++b++=%d", c);
        c=(short) (--b+a++);
        b=4;
        a=5;
        System.out.printf("\n--b+a++=%d", c);
        boolean z=a>b;
        System.out.printf("\na>b-"+ z);
        z=a<=b;
        System.out.printf("\na<=b-"+ z);
        z=a!=b;
        System.out.printf("\na!=b-"+ z);
        z=a<b&&a!=0;
        System.out.printf("\na<b&&a!=0-"+ z);
        z=a>b&&a!=0;
        System.out.printf("\na>b&&a!=0-"+ z);
        z=a<b||a!=0;
        System.out.printf("\na<b||a!=0-"+ z);
        z=a>b||a!=0;
        System.out.printf("\na>b||a!=0-"+ z);
        z=a<b^a!=0;
        System.out.printf("\na<b^a!=0-"+ z);
        z=a>b^a!=0;
        System.out.printf("\na>b^a!=0-"+ z);
        z=!(a>b);
        System.out.printf("\n!(a>b)-"+ z);
        z=a<b&a!=0;
        System.out.printf("\na<b&a!=0-"+ z);
        z=a>b&a!=0;
        System.out.printf("\na>b&a!=0-"+ z);
        z=a<b|a!=0;
        System.out.printf("\na<b|a!=0-"+ z);
        z=a>b|a!=0;
        System.out.printf("\na>b|a!=0-"+ z);
        c=(short) (~a);
        System.out.printf("\nc=~a, c="+ c);
        c=(short) (a>>1);
        System.out.printf("\nc=a>>1, c="+ c);
        c=(short) (a<<1);
        System.out.printf("\nc=a<<1, c="+ c);
        c=(short) (-a>>>1);
        System.out.printf("\nc=-a>>>1, c="+ c);
        c=a;
        System.out.printf("\nc=a, c="+c);
        a+=2;
        System.out.printf("\na+=2, a="+a);
        a-=2;
        a-=1;
        System.out.printf("\na-=1, a="+a);
        a++;
        a*=2;
        System.out.printf("\na*=2, a="+a);
        a/=2;
        a/=2;
        System.out.printf("\na/=2, a="+a);
        a=5;
        a%=2;
        System.out.printf("\na%%=2, a="+a);
        a=5;
        a<<=1;
        System.out.printf("\na<<=1, a="+a);
        a=5;
        a>>=1;
        System.out.printf("\na>>=1, a="+a);
        a=5;
        a&=3;
        System.out.printf("\na&=3, a="+a);
        a=5;
        a|=3;
        System.out.printf("\na|=3, a="+a);
        a=5;
        a^=3;
        System.out.printf("\na^=3, a="+a);
    }

    public void testLong(){
        long a=5, b=4, c;

        System.out.println("\nLong operations:");
        System.out.println("a="+a);
        System.out.print("b="+b);

        c=a+b;
        System.out.printf("\na+b=%d", c);
        c=a-b;
        System.out.printf("\na-b=%d", c);
        c=a/b;
        System.out.printf("\na/b=%d", c);
        c=a*b;
        System.out.printf("\na*b=%d", c);
        c=a%b;
        System.out.printf("\na%%b=%d", c);
        c=++a+b++;
        --a;
        --b;
        System.out.printf("\n++a+b++=%d", c);
        c=b+++b+++b++;
        b -=3;
        System.out.printf("\nb+++b+++b++=%d", c);
        c=--b+a++;
        b++;
        a--;
        System.out.printf("\n--b+a++=%d", c);
        boolean z=a>b;
        System.out.printf("\na>b-"+ z);
        z=a<=b;
        System.out.printf("\na<=b-"+ z);
        z=a!=b;
        System.out.printf("\na!=b-"+ z);
        z=a<b&&a!=0;
        System.out.printf("\na<b&&a!=0-"+ z);
        z=a>b&&a!=0;
        System.out.printf("\na>b&&a!=0-"+ z);
        z=a<b||a!=0;
        System.out.printf("\na<b||a!=0-"+ z);
        z=a>b||a!=0;
        System.out.printf("\na>b||a!=0-"+ z);
        z=a<b^a!=0;
        System.out.printf("\na<b^a!=0-"+ z);
        z=a>b^a!=0;
        System.out.printf("\na>b^a!=0-"+ z);
        z=!(a>b);
        System.out.printf("\n!(a>b)-"+ z);
        z=a<b&a!=0;
        System.out.printf("\na<b&a!=0-"+ z);
        z=a>b&a!=0;
        System.out.printf("\na>b&a!=0-"+ z);
        z=a<b|a!=0;
        System.out.printf("\na<b|a!=0-"+ z);
        z=a>b|a!=0;
        System.out.printf("\na>b|a!=0-"+ z);
        c=~a;
        System.out.printf("\nc=~a, c="+ c);
        c=a>>1;
        System.out.printf("\nc=a>>1, c="+ c);
        c=a<<1;
        System.out.printf("\nc=a<<1, c="+ c);
        c=-a>>>1;
        System.out.printf("\nc=-a>>>1, c="+ c);
        c=a;
        System.out.printf("\nc=a, c="+c);
        a+=2;
        System.out.printf("\na+=2, a="+a);
        a-=2;
        a-=1;
        System.out.printf("\na-=1, a="+a);
        a++;
        a*=2;
        System.out.printf("\na*=2, a="+a);
        a/=2;
        a/=2;
        System.out.printf("\na/=2, a="+a);
        a=5;
        a%=2;
        System.out.printf("\na%%=2, a="+a);
        a=5;
        a<<=1;
        System.out.printf("\na<<=1, a="+a);
        a=5;
        a>>=1;
        System.out.printf("\na>>=1, a="+a);
        a=5;
        a&=3;
        System.out.printf("\na&=3, a="+a);
        a=5;
        a|=3;
        System.out.printf("\na|=3, a="+a);
        a=5;
        a^=3;
        System.out.printf("\na^=3, a="+a);
    }

    public void testDouble(){
        double a=5, b=4, c;

        System.out.println("\nDouble operations:");
        System.out.println("a="+a);
        System.out.print("b="+b);

        c=a+b;
        System.out.printf("\na+b=%f", c);
        c=a-b;
        System.out.printf("\na-b=%f", c);
        c=a/b;
        System.out.printf("\na/b=%f", c);
        c=a*b;
        System.out.printf("\na*b=%f", c);
        c=a%b;
        System.out.printf("\na%%b=%f", c);
        c=++a+b++;
        --a;
        --b;
        System.out.printf("\n++a+b++=%f", c);
        c=b+++b+++b++;
        b -=3;
        System.out.printf("\nb+++b+++b++=%f", c);
        c=--b+a++;
        b++;
        a--;
        System.out.printf("\n--b+a++=%f", c);
        boolean z=a>b;
        System.out.printf("\na>b-"+ z);
        z=a<=b;
        System.out.printf("\na<=b-"+ z);
        z=a!=b;
        System.out.printf("\na!=b-"+ z);
        z=a<b&&a!=0;
        System.out.printf("\na<b&&a!=0-"+ z);
        z=a>b&&a!=0;
        System.out.printf("\na>b&&a!=0-"+ z);
        z=a<b||a!=0;
        System.out.printf("\na<b||a!=0-"+ z);
        z=a>b||a!=0;
        System.out.printf("\na>b||a!=0-"+ z);
        z=a<b^a!=0;
        System.out.printf("\na<b^a!=0-"+ z);
        z=a>b^a!=0;
        System.out.printf("\na>b^a!=0-"+ z);
        z=!(a>b);
        System.out.printf("\n!(a>b)-"+ z);
        z=a<b&a!=0;
        System.out.printf("\na<b&a!=0-"+ z);
        z=a>b&a!=0;
        System.out.printf("\na>b&a!=0-"+ z);
        z=a<b|a!=0;
        System.out.printf("\na<b|a!=0-"+ z);
        z=a>b|a!=0;
        System.out.printf("\na>b|a!=0-"+ z);
        /*  Not Supported commands:
        c=~a;
        System.out.printf("\nc=~a, c="+ c);
        c=a>>1;
        System.out.printf("\nc=a>>1, c="+ c);
        c=a<<1;
        System.out.printf("\nc=a<<1, c="+ c);
        c=-a>>>1;
        System.out.printf("\nc=-a>>>1, c="+ c);
        */
        c=a;
        System.out.printf("\nc=a, c="+c);
        a+=2;
        System.out.printf("\na+=2, a="+a);
        a-=2;
        a-=1;
        System.out.printf("\na-=1, a="+a);
        a++;
        a*=2;
        System.out.printf("\na*=2, a="+a);
        a/=2;
        a/=2;
        System.out.printf("\na/=2, a="+a);
        a=5;
        a%=2;
        System.out.printf("\na%%=2, a="+a);
        a=5;
        /*  Not Supported commands:
        a<<=1;
        System.out.printf("\na<<=1, a="+a);
        a=5;
        a>>=1;
        System.out.printf("\na>>=1, a="+a);
        a=5;
        a&=3;
        System.out.printf("\na&=3, a="+a);
        a=5;
        a|=3;
        System.out.printf("\na|=3, a="+a);
        a=5;
        a^=3;
        System.out.printf("\na^=3, a="+a);
        */
    }

    public void testFloat(){
        float a=5, b=4, c;

        System.out.println("\nFloat operations:");
        System.out.println("a="+a);
        System.out.print("b="+b);

        c=a+b;
        System.out.printf("\na+b=%f", c);
        c=a-b;
        System.out.printf("\na-b=%f", c);
        c=a/b;
        System.out.printf("\na/b=%f", c);
        c=a*b;
        System.out.printf("\na*b=%f", c);
        c=a%b;
        System.out.printf("\na%%b=%f", c);
        c=++a+b++;
        --a;
        --b;
        System.out.printf("\n++a+b++=%f", c);
        c=b+++b+++b++;
        b -=3;
        System.out.printf("\nb+++b+++b++=%f", c);
        c=--b+a++;
        b++;
        a--;
        System.out.printf("\n--b+a++=%f", c);
        boolean z=a>b;
        System.out.printf("\na>b-"+ z);
        z=a<=b;
        System.out.printf("\na<=b-"+ z);
        z=a!=b;
        System.out.printf("\na!=b-"+ z);
        z=a<b&&a!=0;
        System.out.printf("\na<b&&a!=0-"+ z);
        z=a>b&&a!=0;
        System.out.printf("\na>b&&a!=0-"+ z);
        z=a<b||a!=0;
        System.out.printf("\na<b||a!=0-"+ z);
        z=a>b||a!=0;
        System.out.printf("\na>b||a!=0-"+ z);
        z=a<b^a!=0;
        System.out.printf("\na<b^a!=0-"+ z);
        z=a>b^a!=0;
        System.out.printf("\na>b^a!=0-"+ z);
        z=!(a>b);
        System.out.printf("\n!(a>b)-"+ z);
        z=a<b&a!=0;
        System.out.printf("\na<b&a!=0-"+ z);
        z=a>b&a!=0;
        System.out.printf("\na>b&a!=0-"+ z);
        z=a<b|a!=0;
        System.out.printf("\na<b|a!=0-"+ z);
        z=a>b|a!=0;
        System.out.printf("\na>b|a!=0-"+ z);
        /*  Not Supported commands:
        c=~a;
        System.out.printf("\nc=~a, c="+ c);
        c=a>>1;
        System.out.printf("\nc=a>>1, c="+ c);
        c=a<<1;
        System.out.printf("\nc=a<<1, c="+ c);
        c=-a>>>1;
        System.out.printf("\nc=-a>>>1, c="+ c);
        */
        c=a;
        System.out.printf("\nc=a, c="+c);
        a+=2;
        System.out.printf("\na+=2, a="+a);
        a-=2;
        a-=1;
        System.out.printf("\na-=1, a="+a);
        a++;
        a*=2;
        System.out.printf("\na*=2, a="+a);
        a/=2;
        a/=2;
        System.out.printf("\na/=2, a="+a);
        a=5;
        a%=2;
        System.out.printf("\na%%=2, a="+a);
        a=5;
        /*  Not Supported commands:
        a<<=1;
        System.out.printf("\na<<=1, a="+a);
        a=5;
        a>>=1;
        System.out.printf("\na>>=1, a="+a);
        a=5;
        a&=3;
        System.out.printf("\na&=3, a="+a);
        a=5;
        a|=3;
        System.out.printf("\na|=3, a="+a);
        a=5;
        a^=3;
        System.out.printf("\na^=3, a="+a);
        */
    }

    public void testChar(){
        char a=5, b=4, c;

        System.out.println("\nChar operations:");
        System.out.println("a="+a);
        System.out.print("b="+b);

        c=(char) (a+b);
        System.out.printf("\na+b=%c", c);
        c=(char) (a-b);
        System.out.printf("\na-b=%c", c);
        c=(char) (a/b);
        System.out.printf("\na/b=%c", c);
        c=(char) (a*b);
        System.out.printf("\na*b=%c", c);
        c=(char) (a%b);
        System.out.printf("\na%%b=%c", c);
        c=(char) (++a+b++);
        a=5;
        b=4;
        System.out.printf("\n++a+b++=%c", c);
        c=(char) (b+++b+++b++);
        b =4;
        System.out.printf("\nb+++b+++b++=%c", c);
        c=(char) (--b+a++);
        b=4;
        a=5;
        System.out.printf("\n--b+a++=%c", c);
        boolean z=a>b;
        System.out.printf("\na>b-"+ z);
        z=a<=b;
        System.out.printf("\na<=b-"+ z);
        z=a!=b;
        System.out.printf("\na!=b-"+ z);
        z=a<b&&a!=0;
        System.out.printf("\na<b&&a!=0-"+ z);
        z=a>b&&a!=0;
        System.out.printf("\na>b&&a!=0-"+ z);
        z=a<b||a!=0;
        System.out.printf("\na<b||a!=0-"+ z);
        z=a>b||a!=0;
        System.out.printf("\na>b||a!=0-"+ z);
        z=a<b^a!=0;
        System.out.printf("\na<b^a!=0-"+ z);
        z=a>b^a!=0;
        System.out.printf("\na>b^a!=0-"+ z);
        z=!(a>b);
        System.out.printf("\n!(a>b)-"+ z);
        z=a<b&a!=0;
        System.out.printf("\na<b&a!=0-"+ z);
        z=a>b&a!=0;
        System.out.printf("\na>b&a!=0-"+ z);
        z=a<b|a!=0;
        System.out.printf("\na<b|a!=0-"+ z);
        z=a>b|a!=0;
        System.out.printf("\na>b|a!=0-"+ z);
        c=(char) (~a);
        System.out.printf("\nc=~a, c="+ c);
        c=(char) (a>>1);
        System.out.printf("\nc=a>>1, c="+ c);
        c=(char) (a<<1);
        System.out.printf("\nc=a<<1, c="+ c);
        c=(char) (-a>>>1);
        System.out.printf("\nc=-a>>>1, c="+ c);
        c=a;
        System.out.printf("\nc=a, c="+c);
        a+=2;
        System.out.printf("\na+=2, a="+a);
        a-=2;
        a-=1;
        System.out.printf("\na-=1, a="+a);
        a++;
        a*=2;
        System.out.printf("\na*=2, a="+a);
        a/=2;
        a/=2;
        System.out.printf("\na/=2, a="+a);
        a=5;
        a%=2;
        System.out.printf("\na%%=2, a="+a);
        a=5;
        a<<=1;
        System.out.printf("\na<<=1, a="+a);
        a=5;
        a>>=1;
        System.out.printf("\na>>=1, a="+a);
        a=5;
        a&=3;
        System.out.printf("\na&=3, a="+a);
        a=5;
        a|=3;
        System.out.printf("\na|=3, a="+a);
        a=5;
        a^=3;
        System.out.printf("\na^=3, a="+a);
    }

    public void testBoolean(){
        boolean a=true, b=false, c;

        System.out.println("\nBolean operations:");
        System.out.println("a="+a);
        System.out.print("b="+b);
        /*  Not Supported commands:
        c=a+b;
        System.out.printf("\na+b=%d", c);
        c=a-b;
        System.out.printf("\na-b=%d", c);
        c=a/b;
        System.out.printf("\na/b=%d", c);
        c=a*b;
        System.out.printf("\na*b=%d", c);
        c=a%b;
        System.out.printf("\na%%b=%d", c);
        c=++a+b++;
        --a;
        --b;
        System.out.printf("\n++a+b++=%d", c);
        c=b+++b+++b++;
        b -=3;
        System.out.printf("\nb+++b+++b++=%d", c);
        c=--b+a++;
        b++;
        a--;
        System.out.printf("\n--b+a++=%d", c);
        System.out.printf("\na>b-"+ c);
        c=a<=b;
        System.out.printf("\na<=b-"+ c);
        */
        c=a!=b;
        System.out.printf("\na!=b-"+ c);
        c=a&&b;
        System.out.printf("\na&&b-"+ c);
        c=a||b;
        System.out.printf("\na||b-"+ c);
        c=a^b;
        System.out.printf("\na^b-"+ c);
        c=!a;
        System.out.printf("\n!a-"+ c);
        c=a&b;
        System.out.printf("\na&b-"+ c);
        c=a|b;
        System.out.printf("\na|b-"+ c);
        /*  Not Supported commands:
        c=~a;
        System.out.printf("\nc=~a, c="+ c);
        c=a>>1;
        System.out.printf("\nc=a>>1, c="+ c);
        c=a<<1;
        System.out.printf("\nc=a<<1, c="+ c);
        c=-a>>>1;
        System.out.printf("\nc=-a>>>1, c="+ c);
        c=a;
        System.out.printf("\nc=a, c="+c);
        a+=2;
        System.out.printf("\na+=2, a="+a);
        a-=2;
        a-=1;
        System.out.printf("\na-=1, a="+a);
        a++;
        a*=2;
        System.out.printf("\na*=2, a="+a);
        a/=2;
        a/=2;
        System.out.printf("\na/=2, a="+a);
        a=5;
        a%=2;
        System.out.printf("\na%%=2, a="+a);
        a=5;
        a<<=1;
        System.out.printf("\na<<=1, a="+a);
        a=5;
        a>>=1;
        System.out.printf("\na>>=1, a="+a);
        a=5;
        a&=3;
        System.out.printf("\na&=3, a="+a);
        a=5;
        a|=3;
        System.out.printf("\na|=3, a="+a);
        a=5;
        a^=3;
        System.out.printf("\na^=3, a="+a);
        */
    }
}
